### ISSUE TITLE
Process substitution hangs out on Bash 4.4

### ISSUE THREAD

**Issue by esigma5** [tianon/docker-bash#4]
Hello! Not sure whether this is a docker-bash issue or an alpine issue, so excuse me if this is not the right place.

When using Process substiution in the standard way, terminal just hangs out. It seems Bash enters some infinite loop or something, because the process starts consuming too much cpu.
```
emasoero@emasoero-X555LAB:~$ docker run -ti bash:4.4
bash-4.4# cat <(ls)
bin
dev
etc
home
lib
media
mnt
proc
root
run
sbin
srv
sys
tmp
usr
var
^C^C
```

I manually installed bash 4.4 on an ubuntu docker image (16.04) and it works fine

**Comment by tianon** [comment]
Oh wow, this is a bizarre one! :+1:

I'm _guessing_ this is an issue with the way we compile Bash, but it's hard to say for certain since Alpine upstream doesn't have Bash 4.4 yet (https://pkgs.alpinelinux.org/packages?name=bash); it could very well be some kind of odd musl-related issue.  Definitely needs more digging to figure out what's going on. :disappointed:

**Comment by tianon** [comment]
It appears to only exhibit when we're interactive, too:
```console
$ docker run -it --rm bash:4.4 -c 'cat <(ls)'
bin
dev
etc
home
lib
media
mnt
proc
root
run
sbin
srv
sys
tmp
usr
var
$ 
```

**Edit:** nothing to do with TTY though!
```console
$ docker run -i --rm bash:4.4 <<<'cat <(ls)'
bin
dev
etc
home
lib
media
mnt
proc
root
run
sbin
srv
sys
tmp
usr
var

(hangs)
```

**Comment by tianon** [comment]
Turns out this is likely an Alpine-related issue!

See https://github.com/gliderlabs/docker-alpine/issues/363 and https://bugs.alpinelinux.org/issues/8236.

**Comment by unode** [comment]
See also https://bugs.alpinelinux.org/issues/8098.
The bug was closed since the packaging issue was solved but the underlying problem remained.

Downgrading and compiling bash from source works though and is currently the workaround used [here](https://github.com/luispedro/ngless/blob/master/build-scripts/docker_bases/alpine/Dockerfile#L33).

**Comment by jumanjiman** [comment]
Bizarrely, this issue does not occur on https://labs.play-with-docker.com/

IOW, on play-with-docker start an alpine:edge container and attempt to reproduce.
None of the reproducers hang when using play-with-docker.

However, the reproducers *do hang* in my local dev environments.

This seems to rule out process substitution by itself.
Perhaps it's some combination of tty handling and process substitution.

**Comment by ncopa** [comment]
> @unode See also https://bugs.alpinelinux.org/issues/8098.
> The bug was closed since the packaging issue was solved but the underlying problem remained.

I think it was closed after fixing so the patches was actually applied. 
https://github.com/alpinelinux/aports/commit/cec73eedb763b803897e98f0a5b3934dc4be1fdd

I am not able to reproduce it on my work desktop, nor in lxc containers, so the issue was probably resolved with some of the upstream bash patches.

But I can still reproduce it in docker, so this is weird.

Another workaround may be to not use bash at all with configure script:
````sh
    CONFIG_SHELL=/bin/ash ./configure ...
````

**Comment by ncopa** [comment]
I think we should report this upstream. This will be difficult to debug and code is non-trivial to follow and understand. I am not convinced the bug is in alpine or musl, even if the problem does not show on glibc distros. Could be some wrong assumptions regarding signal handling or similar.

**Comment by ncopa** [comment]
Turns out to be a bug in musl after all. A fix is on the way...
http://www.openwall.com/lists/musl/2017/12/07/7

**Comment by ncopa** [comment]
Actually its a bug in bash too. It can be reproduced with glibc too:
````sh
ulimit -u 9223372036854775807
bash -c 'sleep 1 & wait $!'
````

Will fix bash too while at it.

**Comment by tianon** [comment]
You're a hero, @ncopa :heart:

For the peanut gallery, this was fixed in Alpine's `bash` package in https://github.com/alpinelinux/aports/commit/3239e62fb1c7968e923016358345a4dcc7e2f87d (`bash-4.4.12-r2`) and filed upstream with Bash in https://lists.gnu.org/archive/html/bug-bash/2017-12/msg00025.html (and confirmed receipt by Chet in https://lists.gnu.org/archive/html/bug-bash/2017-12/msg00026.html).

I think while Chet figures out what he's going to do about this bug officially upstream, we should likely temporarily apply Alpine's patch for 4.4 (since 4.3 and below are unaffected).

**Comment by ncopa** [comment]
looks like it does not solve it for 32 bit architectures. https://bugs.alpinelinux.org/issues/8447
I could reproduce it with `i386/bash` image. Should I open new ticket or do we want re-open this?

**Comment by tianon** [comment]
I'll reopen, thanks :+1: :heart:

**Comment by ncopa** [comment]
I followed up upstream with a new proposed [patch](http://lists.gnu.org/archive/html/bug-bash/2018-02/msg00037.html), which I also pushed to [alpine linux](https://git.alpinelinux.org/cgit/aports/commit/?h=3.7-stable&id=55aa74e4c16a52e60a19939e12dedaceea1cf13a).

**Comment by tianon** [comment]
I've tried reproducing this (on 5.0 and 4.4) by removing the patch we're applying and it doesn't seem to be reproducible anymore (on any of Alpine 3.9, Alpine 3.10, amd64, i386).  Was this fixed in one of the minor patches to Bash 4.4 perhaps?

**Comment by tianon** [comment]
Looking through https://ftp.gnu.org/gnu/bash/bash-4.4-patches/, nothing after we first started experiencing this seems related at a glance. :confused:

Is it possible a change in `musl` mitigated this too?

**Comment by tianon** [comment]
Confirmed, I had to go all the way back to Alpine 3.6 in order to reproduce the original issue.
